// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZoa66cmXxp-hpoy6ulAs93GQ8nWVp5rI',
    appId: '1:916714729349:web:0b5da0b6234f5f0b3d9eec',
    messagingSenderId: '916714729349',
    projectId: 'fitflex-2146b',
    authDomain: 'fitflex-2146b.firebaseapp.com',
    databaseURL: 'https://fitflex-2146b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fitflex-2146b.appspot.com',
    measurementId: 'G-LEDTEZ2T2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm3ejgeh7OPR6_wjDEjBnjn__26ylIx7c',
    appId: '1:916714729349:android:2f3b21f078d7ccdb3d9eec',
    messagingSenderId: '916714729349',
    projectId: 'fitflex-2146b',
    databaseURL: 'https://fitflex-2146b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fitflex-2146b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl8jGATPIGY5KKTzQ3OYnhoT4VW_TV9BM',
    appId: '1:916714729349:ios:727693e7a8a5796d3d9eec',
    messagingSenderId: '916714729349',
    projectId: 'fitflex-2146b',
    databaseURL: 'https://fitflex-2146b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fitflex-2146b.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl8jGATPIGY5KKTzQ3OYnhoT4VW_TV9BM',
    appId: '1:916714729349:ios:5d3efe7deef21e3f3d9eec',
    messagingSenderId: '916714729349',
    projectId: 'fitflex-2146b',
    databaseURL: 'https://fitflex-2146b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fitflex-2146b.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
